---
dependencies:
  - common
  - edxapp_common
  - browsers
  - role: jenkins_master
    jenkins_plugins: "{{ jenkins_tools_plugins }}"
    jenkins_version: "{{ jenkins_tools_version }}"
    jenkins_deb_url: "https://pkg.jenkins.io/debian-stable/binary/jenkins_{{ jenkins_version }}_all.deb"
    jenkins_custom_plugins: []
    jenkins_bundled_plugins: "{{ jenkins_tools_bundled_plugins }}"
